### PR TITLE
Update guzzlehttp/guzzle requirement

### PR DESCRIPTION
**Pull request by bnzo**
Update guzzle dependency to work with Laravel 8

### CODE REVIEW

**Comment by thyyppa** [comment]
Awesome, thank you!

**Comment by bnzo** [comment]
You’re welcome, thanks for your work on this repo!

I have a question regarding a specific need:

I need to retrieve FM valuelists from layout metadata, this REST call: https://fm.mutesymphony.com/fmi/data/apidoc/#operation/layoutMetadata <https://fm.mutesymphony.com/fmi/data/apidoc/#operation/layoutMetadata>
Basically to reproduce existing dropdown lists from FM in Laravel

I can work on it but I prefer you define method signatures and interfaces, maybe something like:

$fm->layout(‘layout’)->get()
$fm->layout(‘layout’)->metadata->get()
$fm->metadata(‘layout’)->get()

Or this one should be more explicit:
$fm->valueList(‘layout’, ‘fieldName’)

Thanks,

Regards,

N

**Comment by thyyppa** [comment]
That all sounds totally logical to me!

I think adding `$fm->valueList($layout, $field)` and `$fm->fieldMeta($layout, $field)` to the interface would be great additions. 

I don't actually have access to a filemaker server at the moment, but I pushed this to a [branch](https://github.com/thyyppa/fluent-fm/tree/field_meta) going solely off of the [filemaker dapi docs](https://fmhelp.filemaker.com/docs/18/en/dataapi/#get-metadata_get-layout-metadata).

Want to test it out against an actual server?

**Comment by bnzo** [comment]
Great!

I made a Database available for you to test it on my server, feel free to use it :)

It works with the following code after a quick fix, I made a PR 👍🏼

        $this->fm = new FluentFMRepository([
            'file' => 'fluent-fm',
            'host' => 'fabrication.isiprint.net',
            'user' => 'thyyppa',
            'pass' => 'fluent-fm-20201002',
        ]);
        
        $meta = $this->fm->fieldMeta('table_a', 'field_aa');
        $list = $this->fm->valueList('table_a', 'field_aa');

Cheers,

N

**Pull request merged**
